name: ESLint

on: [ push ]

jobs:
  prettier-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Run ESLint
        run: |
          yarn install
          yarn eslint
